# Generated by Django 3.0.6 on 2020-05-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('logo', models.ImageField(default='logo.jpg', upload_to='media/logos')),
                ('address', models.TextField()),
                ('current_viewers', models.IntegerField()),
                ('total_viewers', models.IntegerField()),
            ],
        ),
    ]
