# Generated by Django 3.0.6 on 2020-05-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='current_viewers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_viewers',
            field=models.IntegerField(default=0),
        ),
    ]
